### ISSUE TITLE
Missing lua files while loading ledokol.lua

### ISSUE THREAD

**Issue by DooMFeaR** [Verlihub/ledokol#15]
Verlihub 1.3.0 running on Ubuntu 18.04 LTS.
Lua 5.4.4  - compiled from source.
Ledokol git cloned.
-----------------------

Doing !luaload ledokol.lua

>  [23:59:26] <Verlihub> Plugin loaded.
>  [23:59:35] <# Ledokol> Warning: Unable to load LuaSocket module: /etc/verlihub/scripts/ledokol.lua:26439: module 'socket' not found:
>  	no field package.preload['socket']
>  	no file '/usr/local/share/lua/5.2/socket.lua'
>  	no file '/usr/local/share/lua/5.2/socket/init.lua'
>  	no file '/usr/local/lib/lua/5.2/socket.lua'
>  	no file '/usr/local/lib/lua/5.2/socket/init.lua'
>  	no file '/usr/share/lua/5.2/socket.lua'
>  	no file '/usr/share/lua/5.2/socket/init.lua'
> 
> 	no file './socket.lua'
> 	no file '/usr/local/lib/lua/5.2/socket.so'
> 	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/socket.so'
> 	no file '/usr/lib/lua/5.2/socket.so'
> 	no file '/usr/local/lib/lua/5.2/loadall.so'
> 	no file './socket.so'

I even tried to compile **5.2** , even tryied to apt install lua5.2 , but seems like the files are not going into those folders!

Any help would be appreciated!

**Comment by RoLex** [comment]
This issue is about LuaSocket module, which is optional in Ledokol, the script simply notifies you that it's missing. Warning is not an error.

But you have another problem, which is a common problem. You have Lua 5.2 installed via package manager, and you have Lua 5.4 installed via sources. You need to remove one of those, so there is only one left, otherwise compiler has a hard time to make a choise. You said that you compiled 5.4 while Ledokol tries to load stuff using 5.2. Once you remove one of those, you need to recompile Verlihub in order to point it to correct Lua version.

Next issue with Lua 5.4.4 is that I could not get it working with Verlihub yet, the last version that works is currently 5.4.2. If you look in `!luaversion` you will probably see 5.2 there right now.

And one more issue with you OS, Ubuntu 18.04 is very old, it will no longer be supported in early 2023. If you are setting up a new server, I would directly advise to install something that is newer. But it's your choise ofcourse.

**Comment by DooMFeaR** [comment]
Hello and thanks for reply!
I will recompile Verlihub today on a newer version of Ubuntu. I will push it up to Ubuntu server 20.04 LTS. Doing _**!luaversion**_  outputs: 
` [*] Lua version: Lua 5.2 [Lua 5.2.4]
 [*] Copyright: Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
 [*] Authors: R. Ierusalimschy, L. H. de Figueiredo, W. Celes`


Thanks for all your help! I definately take care of your advices.
